#spring:
#  datasource:
#    url: jdbc:sqlserver://save-up-server.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: admin-saveup
#    password: Gfgrupo9
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL57Dialect
#      globally_quoted_identifiers: true
#
#
#server:
#  port: 8080